name: Run WBWAI inference and metric

on:
  repository_dispatch:
    types: [wbwai_update]
  workflow_dispatch:
    inputs:
      ref:
        description: "WBWAI branch that triggered this run" 
        required: false
      sha:
        description: "WBWAI commit SHA"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out WBWMonitor code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        env:
          WBWAI_REF: ${{ github.event.client_payload.ref }}
          WBWAI_SHA: ${{ github.event.client_payload.sha }}
        run: |
          echo "Triggered by WBWAI ref=${WBWAI_REF} sha=${WBWAI_SHA}"
          python main.py